// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOs7PiKrhx1U0idWS3Sv3U3VUybWwh40I',
    appId: '1:983877210087:web:fa53b535acb3d4e75ef742',
    messagingSenderId: '983877210087',
    projectId: 'planner-list-28e16',
    authDomain: 'planner-list-28e16.firebaseapp.com',
    storageBucket: 'planner-list-28e16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAacG4PgnDMBcXwny698rRMy7d9dWzthGc',
    appId: '1:983877210087:android:681833e387886cc45ef742',
    messagingSenderId: '983877210087',
    projectId: 'planner-list-28e16',
    storageBucket: 'planner-list-28e16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8sT59OQ1n3A1PS5j5S4b8fBAk4DwOG5s',
    appId: '1:983877210087:ios:29eeb19424a45d845ef742',
    messagingSenderId: '983877210087',
    projectId: 'planner-list-28e16',
    storageBucket: 'planner-list-28e16.appspot.com',
    iosBundleId: 'com.example.codingMindsSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8sT59OQ1n3A1PS5j5S4b8fBAk4DwOG5s',
    appId: '1:983877210087:ios:164c6442fe6c986c5ef742',
    messagingSenderId: '983877210087',
    projectId: 'planner-list-28e16',
    storageBucket: 'planner-list-28e16.appspot.com',
    iosBundleId: 'com.example.codingMindsSample.RunnerTests',
  );
}
